/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/admin/doctors/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_admin_doctors_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["accounts_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounts_me_retrieve"];
        put: operations["accounts_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["accounts_me_partial_update"];
        trace?: never;
    };
    "/api/accounts/setup-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_setup_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["accounts_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_list"];
        put?: never;
        post: operations["appointments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["appointments_retrieve"];
        put: operations["appointments_update"];
        post?: never;
        delete: operations["appointments_destroy"];
        options?: never;
        head?: never;
        patch: operations["appointments_partial_update"];
        trace?: never;
    };
    "/api/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["doctors_list"];
        put?: never;
        post: operations["doctors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["doctors_retrieve"];
        put: operations["doctors_update"];
        post?: never;
        delete: operations["doctors_destroy"];
        options?: never;
        head?: never;
        patch: operations["doctors_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountDoctorProfile: {
            readonly id: number;
            specialization?: string | null;
            qualification?: string | null;
            /** Format: decimal */
            consultation_fee?: string;
            chamber_address?: string | null;
            is_available?: boolean;
        };
        AdminDoctorCreate: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            phone_number?: string;
            specialization?: string;
            qualification?: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            consultation_fee: string;
            chamber_address?: string;
        };
        Appointment: {
            readonly id: number;
            readonly patient: number;
            /**
             * Email address
             * Format: email
             */
            readonly patient_email: string;
            doctor: number;
            readonly doctor_detail: components["schemas"]["DoctorProfile"];
            /** Format: date */
            appointment_date: string;
            /** Format: time */
            time_slot_start: string;
            /** Format: time */
            time_slot_end: string;
            symptoms_note?: string | null;
            /** Format: decimal */
            readonly total_fee: string | null;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DoctorProfile: {
            readonly id: number;
            readonly user: number;
            readonly user_details: components["schemas"]["UserProfile"];
            specialization?: string | null;
            qualification?: string | null;
            /** Format: decimal */
            consultation_fee?: string;
            chamber_address?: string | null;
            is_available?: boolean;
        };
        PasswordSetup: {
            uid: string;
            token: string;
            new_password: string;
        };
        PatchedAppointment: {
            readonly id?: number;
            readonly patient?: number;
            /**
             * Email address
             * Format: email
             */
            readonly patient_email?: string;
            doctor?: number;
            readonly doctor_detail?: components["schemas"]["DoctorProfile"];
            /** Format: date */
            appointment_date?: string;
            /** Format: time */
            time_slot_start?: string;
            /** Format: time */
            time_slot_end?: string;
            symptoms_note?: string | null;
            /** Format: decimal */
            readonly total_fee?: string | null;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedDoctorProfile: {
            readonly id?: number;
            readonly user?: number;
            readonly user_details?: components["schemas"]["UserProfile"];
            specialization?: string | null;
            qualification?: string | null;
            /** Format: decimal */
            consultation_fee?: string;
            chamber_address?: string | null;
            is_available?: boolean;
        };
        PatchedUserProfile: {
            readonly id?: number;
            /**
             * Email address
             * Format: email
             */
            readonly email?: string;
            readonly role?: components["schemas"]["RoleEnum"];
            phone_number?: string | null;
            readonly is_verified?: boolean;
            readonly doctor_profile?: components["schemas"]["AccountDoctorProfile"];
            readonly patient_profile?: components["schemas"]["PatientProfile"];
        };
        PatientProfile: {
            readonly id: number;
            emergency_contact?: string | null;
        };
        /**
         * @description * `ADMIN` - Admin
         *     * `DOCTOR` - Doctor
         *     * `PATIENT` - Patient
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "DOCTOR" | "PATIENT";
        /**
         * @description * `PENDING` - Pending
         *     * `CONFIRMED` - Confirmed
         *     * `CANCELLED` - Cancelled
         *     * `COMPLETED` - Completed
         * @enum {string}
         */
        StatusEnum: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        UserProfile: {
            readonly id: number;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
            phone_number?: string | null;
            readonly is_verified: boolean;
            readonly doctor_profile: components["schemas"]["AccountDoctorProfile"];
            readonly patient_profile: components["schemas"]["PatientProfile"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_admin_doctors_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDoctorCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminDoctorCreate"];
                "multipart/form-data": components["schemas"]["AdminDoctorCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDoctorCreate"];
                };
            };
        };
    };
    accounts_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    accounts_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    accounts_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProfile"];
                "multipart/form-data": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    accounts_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProfile"];
                "multipart/form-data": components["schemas"]["PatchedUserProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    accounts_setup_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSetup"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordSetup"];
                "multipart/form-data": components["schemas"]["PasswordSetup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordSetup"];
                };
            };
        };
    };
    accounts_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    appointments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"][];
                };
            };
        };
    };
    appointments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Appointment"];
                "application/x-www-form-urlencoded": components["schemas"]["Appointment"];
                "multipart/form-data": components["schemas"]["Appointment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    appointments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    appointments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Appointment"];
                "application/x-www-form-urlencoded": components["schemas"]["Appointment"];
                "multipart/form-data": components["schemas"]["Appointment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    appointments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    appointments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAppointment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAppointment"];
                "multipart/form-data": components["schemas"]["PatchedAppointment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    doctors_list: {
        parameters: {
            query?: {
                is_available?: boolean;
                max_fee?: number;
                min_fee?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                specialization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"][];
                };
            };
        };
    };
    doctors_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DoctorProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["DoctorProfile"];
                "multipart/form-data": components["schemas"]["DoctorProfile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
    doctors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this doctor profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
    doctors_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this doctor profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DoctorProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["DoctorProfile"];
                "multipart/form-data": components["schemas"]["DoctorProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
    doctors_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this doctor profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    doctors_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this doctor profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDoctorProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDoctorProfile"];
                "multipart/form-data": components["schemas"]["PatchedDoctorProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
}
